spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://localhost:5433/companies
    username: admin
    password: Perritos12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
