spring:
  application:
    name: companies-crud
  datasource:
    url: jdbc:postgresql://localhost:5433/companies
    username: admin
    password: Perritos12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /companies-crud
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}
