spring:
  application:
    name: report-ms
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  cloud:
    compatibility-verifier:
      enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /report-ms
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 10000
        loggerLevel: full
